#!/bin/bash
bat=/org/freedesktop/UPower/devices/battery_BAT0
percent=$(upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep -E "percentage" | awk -F'percentage:' '{gsub(/[^0-9]/, "", $2); print $2}')
state=$(upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep -E "state" | awk -F'state:' '{gsub(/[ ]/,"", $2); print $2}')
#echo "$state"

multiples=(10 20 30 40 50 60 70 80 90 100)
indicators=("󰁺" "󰁻" "󰁼" "󰁽" "󰁾" "󰁿" "󰂀" "󰂁" "󰂂" "󰁹")
if [ "$state" == "fully-charged" ]; then
    echo ""
elif [ "$state" == "charging" ]; then
    echo "󰂄"
else
    for i in "${!multiples[@]}"; do
      if [ "$percent" -le "${multiples[$i]}" ]; then
        echo "${indicators[$i]}"
        break
      fi
    done
fi

