require('config.alpha')
require('config.barbar')
require('config.cmp')
require('config.gitsigns')
require('config.ibl')
require('config.lsp_config')
require('config.lualine')
-- require('config.feline')
require('config.luasnip')
require('config.nvim_cursorline')
require('config.nvim_tree')
require('config.obsidian')
require('config.satellite')
require('config.session-manager')
require('config.telescope')
require('config.treesitter')
require('config.workflows')
